import { StyleSheet, Dimensions } from "react-native";
import Color from "../Color";

const { width: screenWidth } = Dimensions.get("window");
export const DRAWER_WIDTH = screenWidth * 0.8;

export default StyleSheet.create({
  backdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 998,
  },
  drawer: {
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    width: DRAWER_WIDTH,
    backgroundColor: Color.white,
    zIndex: 999,
    shadowColor: Color.shadowLg,
    shadowOffset: {
      width: 2,
      height: 0,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  drawerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 20,
    backgroundColor: Color.white,

    shadowColor: Color.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  searchContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Color.gray50,
    borderWidth: 1,
    borderColor: Color.gray200,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 12,
  },
  headerContent: {
    flex: 1,
  },
  drawerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: Color.black,
    letterSpacing: -0.5,
    marginBottom: 2,
  },
  drawerSubtitle: {
    fontSize: 14,
    fontWeight: "500",
    color: Color.gray600,
    letterSpacing: -0.1,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Color.gray100,
    shadowColor: Color.shadow,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  closeIcon: {
    fontSize: 20,
    fontWeight: "600",
    color: Color.gray700,
  },
  newThreadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 18,
    marginHorizontal: 16,
    marginVertical: 12,
    backgroundColor: Color.black,
    borderRadius: 12,
    shadowColor: Color.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  newThreadIcon: {
    fontSize: 18,
    fontWeight: "600",
    color: Color.white,
    marginRight: 8,
  },
  newThreadText: {
    fontSize: 16,
    fontWeight: "600",
    color: Color.white,
    letterSpacing: -0.2,
  },
  threadList: {
    flex: 1,
    paddingTop: 8,
    paddingBottom: 16,
  },
  threadSeparator: {
    height: 1,
    backgroundColor: Color.gray100,
    marginHorizontal: 16,
  },
  threadItem: {
    paddingHorizontal: 12,
    paddingVertical: 18,
    marginHorizontal: 16,
    marginVertical: 4,
    backgroundColor: Color.white,
    borderRadius: 12,
    shadowColor: Color.shadow,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  activeThreadItem: {
    backgroundColor: Color.gray50,
    borderColor: Color.black,
    borderWidth: 2,
    shadowColor: Color.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  chatsHeader: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: Color.white,
  },
  chatsHeaderText: {
    fontSize: 18,
    fontWeight: "600",
    color: Color.gray800,
    letterSpacing: -0.3,
  },
  threadContent: {
    flex: 1,
  },
  threadTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: Color.gray800,
    marginBottom: 6,
    letterSpacing: -0.2,
  },
  activeThreadTitle: {
    color: Color.black,
    fontWeight: "700",
  },
  threadLastMessage: {
    fontSize: 14,
    color: Color.gray600,
    marginBottom: 6,
    lineHeight: 18,
  },
  activeThreadLastMessage: {
    color: Color.gray700,
    fontWeight: "500",
  },
  threadTimestamp: {
    fontSize: 12,
    color: Color.gray500,
    fontWeight: "500",
  },
  activeThreadTimestamp: {
    color: Color.gray600,
    fontWeight: "600",
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingVertical: 48,
  },
  emptyStateContent: {
    alignItems: "center",
  },
  emptyStateIcon: {
    fontSize: 48,
    marginBottom: 16,
    textAlign: "center",
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: Color.gray800,
    marginBottom: 8,
    textAlign: "center",
  },
  emptyStateSubtitle: {
    fontSize: 14,
    color: Color.gray600,
    textAlign: "center",
    lineHeight: 20,
  },

  threadEmptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingVertical: 48,
  },
  threadEmptyIcon: {
    fontSize: 48,
    marginBottom: 16,
    textAlign: "center",
  },
  threadEmptyTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
    textAlign: "center",
  },
  threadEmptySubtitle: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 20,
  },

  searchInput: {
    flex: 1,
    fontSize: 16,
    color: Color.gray800,
    paddingVertical: 8,
    paddingHorizontal: 8,
  },
  searchIcon: {
    fontSize: 20,
    marginRight: 8,
    color: Color.gray500,
  },

  // Error styles
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingVertical: 48,
    backgroundColor: Color.background,
  },
  errorContent: {
    alignItems: "center",
    backgroundColor: Color.white,
    padding: 32,
    borderRadius: 16,
    shadowColor: Color.shadowLg,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    maxWidth: 320,
    width: "100%",
  },
  errorIcon: {
    marginBottom: 16,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: Color.destructive,
    marginBottom: 12,
    textAlign: "center",
    letterSpacing: -0.3,
  },
  errorMessage: {
    fontSize: 16,
    color: Color.gray600,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
    letterSpacing: -0.1,
  },
  errorRetryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Color.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
    shadowColor: Color.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  errorRetryIcon: {
    marginRight: 8,
  },
  errorRetryText: {
    color: Color.white,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
});
